### PR TITLE
[Security] Update cocoapods & dependencies 

### PR DESCRIPTION
**Pull request by lukeswitz**
Cocoapods 1.9.3 -> 1.10.0 (stable)

### CODE REVIEW

**Comment by farktronix** [comment]
Thanks! This is good to have.

It looks like I still need to figure out why Travis is failing. I'll give my branch another shot now- maybe the Realm issues have been sorted out now that 10.0 is live.

**Comment by farktronix** [comment]
No dice- I'm getting the same compile error under Travis on my branch. I'm not reproducing it locally using xcodebuild though.

**Comment by lukeswitz** [comment]
> No dice- I'm getting the same compile error under Travis on my branch. I'm not reproducing it locally using xcodebuild though.

Same, it’s an issue with Realm and the Travis build environment combined with two scripts hosted here. I’ve gotten it to pass, but you have to explicitly update the Travis environment in a way that forces it to perform a twenty minute task. Too much time wasted here, how can I assist in adding & fixing shows? Is that hard coded into your .weasly API or does it use LMA dynamically?

**Comment by lukeswitz** [comment]
Realm is for sure the issue, downgrading I was able to get a passing Travis build. Lots of time wasted on CI here, but targeting archs seem the problem 32 vs 64
```
Undefined symbols for architecture x86_64
2629> Symbol: realm::ConstLstIf<realm::Timestamp>::max(unsigned long*) const
2630> Referenced from: vtable for realm::Lst<realm::Timestamp> in thread_safe_reference.o
```

**Pull request merged**
